#!/bin/sh
# Volumen fijo: espera a que wireplumber tenga la salida de audio lista
(
	for i in $(seq 20); do
		wpctl set-volume @DEFAULT_AUDIO_SINK@ @VOLUME@% 2>/dev/null && wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && break
		sleep 1
	done
) &
"@KDIR@/relanzar.sh" &
